
services:
  
  database:
    container_name: database
    image: postgres
    environment:
      POSTGRES_DB: db_associates
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: vini123
      POSTGRES_HOST_AUTH_METHOD: trust
      PGDATA: /data/postgres
    volumes:
      - postgres_data:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped


  backend:
    build: ./Backend
    volumes:
      - ./Backend:/code
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=postgresql://postgres:vini123@database:5432/db_associates
    depends_on:
      - database
  
  nginx:
    image: nginx:stable-alpine # Imagem Nginx leve
    container_name: nginx_proxy
    ports:
      # Expõe a porta 80 do Nginx (e do contêiner) para o mundo externo
      - "80:80"
      # - "443:443" 
    volumes:
      # Mapeia o arquivo de configuração local para o local de configuração do Nginx no contêiner
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend # Garante que o backend esteja funcionando antes de iniciar o Nginx
    restart: unless-stopped
  

volumes:
  postgres_data:
  


